services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - DOTORG_ENV=development
      - DOTORG_BACKEND_BASICAUTH_USER=admin
      - DOTORG_BACKEND_BASICAUTH_PASS=password
      - DOTORG_BACKEND_SENTRY_DSN=https://7ef396d183c3b386b9053670943f99ca@o4509260716703744.ingest.de.sentry.io/4509329883005008
    restart: unless-stopped 